/**:
  ros__parameters:
    can_assign_matrix:
      #UNKNOWN, CAR, TRUCK, BUS, TRAILER, MOTORBIKE, BICYCLE, PEDESTRIAN <-roi_msg
      [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0, # UNKNOWN <-detected_objects
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0, # CAR
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0, # TRUCK
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0, # BUS
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0, # TRAILER
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0, # MOTORBIKE
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0, # BICYCLE
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
      ] # PEDESTRIAN
